/**
 * Created by jason on 2016/1/8.
 */
$(function(){
    //点击登录按钮
    $(".login").click(function(){
        $(".big_form").css({
            display:"block"
        })
    });
    $(".close").click(function(){
        $(".big_form").css({
            display:"none"
        })
    });
    //图片遮罩层
    $(".list").mouseover(function(){
        $(this).find($(".will_show")).css({
            display:"block"
        })
    });
    $(".list").mouseout(function(){
        $(this).find($(".will_show")).css({
            display:"none"
        })
    });
    //鼠标移入动画
    $(".big").mouseenter(function(){
        $(this).find($(".b1")).animate({
            width:"100%",
            marginLeft:"-50%"
        },500);
        $(this).find($(".left")).delay(500).animate({
            height:"100%"
        },500);
        $(this).find($(".right")).delay(500).animate({
            height:"100%"
        },500);
        $(this).find($(".top1")).delay(1000).animate({
            width:"100%"
        },500);
        $(this).find($(".top2")).delay(1000).animate({
            width:"100%"
        },500);
    });
    //鼠标移除动画
    $(".big").mouseleave(function(){
        $(this).find($(".top1")).animate({
            width:"0"
        },500);
        $(this).find($(".top2")).animate({
            width:"0"
        },500);
        $(this).find($(".left")).delay(500).animate({
            height:"0"
        },500);
        $(this).find($(".right")).delay(500).animate({
            height:"0"
        },500);
        $(this).find($(".b1")).delay(1000).animate({
            width:"0",
            marginLeft:"0"
        },500);
    });
});