document.writeln("<section class=\"fotit\">");
document.writeln("<div class=\"fotitMain pd hd\">");
document.writeln("<h4><img src=\"images/img9.png\"></h4>");
document.writeln("<div class=\"fothsL\">");
document.writeln("<div class=\"tits hd\">");
document.writeln("  <span class=\"wsd1\">关于英国豪迈</span><span class=\"wsd2\">业务合作</span><span class=\"wsd3\">多媒体资源</span><span class=\"wsd4\">法律声明</span>");
document.writeln("</div>");
document.writeln("<div class=\"uls hd\">");
document.writeln("  <ul class=\"wsd1\">");
document.writeln("      <li><a href=\"/aboutus/strategy\" target=\"_self\">集团简介</a></li>");
document.writeln("      <li><a href=\"/aboutus/subsidiaries\" target=\"_self\">子公司品牌</a></li>");
document.writeln("      <li><a href=\"/career/jobs\" target=\"_self\">求职招聘</a></li>");
document.writeln("      <li><a href=\"/aboutus/contact\" target=\"_self\">联系我们</a></li>");
document.writeln("      <li><a href=\"/sitemap\" target=\"_self\">网站地图</a></li>");
document.writeln("  </ul>");
document.writeln("  <ul class=\"wsd2\">");
document.writeln("      <li><a href=\"#\" target=\"_self\">营销推广</a></li>");
document.writeln("      <li><a href=\"/news/partnership\" target=\"_self\">商业伙伴</a></li>");
document.writeln("      <li><a href=\"#\" target=\"_self\">技术支持</a></li>");
document.writeln("      <li><a href=\"/acquisitions/conditions\" target=\"_self\">收购要约</a></li>");
document.writeln("      <li><a href=\"#\" target=\"_self\">友情链接</a></li>");
document.writeln("  </ul>");
document.writeln("  <ul class=\"wsd3\">");
document.writeln("      <li><a href=\"#\" target=\"_self\">豪迈图库</a></li>");
document.writeln("      <li><a href=\"/news/videos\" target=\"_self\">豪迈视频</a></li>");
document.writeln("      <li><a href=\"#\" target=\"_self\">报表和白皮书</a></li>");
document.writeln("      <li><a href=\"/resources/downloads\" target=\"_self\">技术文档</a></li>");
document.writeln("      <li><a href=\"#\" target=\"_self\">新闻简报</a></li>");
document.writeln("  </ul>");
document.writeln("  <ul class=\"wsd4\">");
document.writeln("      <li><a href=\"/statements/privacy\" target=\"_self\">隐私政策</a></li>");
document.writeln("      <li><a href=\"/statements/terms\" target=\"_self\">服务条款</a></li>");
document.writeln("      <li><a href=\"/statements/disclaimer\" target=\"_self\">免责声明</a></li>");
document.writeln("      <li><a href=\"/statements/accessibility\" target=\"_self\">网站使用说明</a></li>");
document.writeln("  </ul>");
document.writeln("</div> ");
document.writeln("");
document.writeln("<div class=\"find hd\">");
document.writeln("<a href=\"#\"><img src=\"images/img11.png\"></a>");
document.writeln("<a href=\"#\"><img src=\"images/img12.png\"></a>");
document.writeln("<a href=\"#\"><img src=\"images/img13.png\"></a>");
document.writeln("<a href=\"#\"><img src=\"images/img14.png\"></a>");
document.writeln("<a href=\"#\"><img src=\"images/img15.png\"></a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</section>");
document.writeln("<div class=\"footAdd hd\">");
document.writeln("	<dl class=\"pd\">");
document.writeln("		<dt>集团总公司：</dt>");
document.writeln("		<dd><a href=\"http://www.halma.com/\">豪迈股份有限公司（集团总部）</a> | <a href=\"http://www.halma.com/\">豪迈控股有限公司（北美总公司）</a> | <a href=\"http://halma.in/\">豪迈印度经纪有限公司（印度总公司）</a> | <a href=\"/\">英国豪迈国际有限公司（中国总公司）</a></dd>");
document.writeln("		<dt>过程安全事业部子公司：</dt>");
document.writeln("		<dd><a href=\"http://www.kirkkey.com/\">柯克钥匙联锁</a> | <a href=\"http://www.elfab.com/cn\">安赛科</a> | <a href=\"http://www.castell.com.cn/\">柯施泰工业安全设备</a> | <a href=\"http://www.servtrayvou.com.cn/\">赛特福工业安全</a> | <a href=\"http://www.fortressinterlocks.com.cn/\">福帝斯联锁</a> | <a href=\"http://www.crowcon.com.cn/\">科尔康安全设备</a> | <a href=\"http://www.netherlocks.com.cn/\">耐德安全系统</a> | <a href=\"http://www.smithflowcontrol.com.cn/\">史密斯流体控制</a> | <a href=\"http://www.elfab.com/zh-hant/\">安防保</a></dd>");
document.writeln("		<dt>基础设施安全事业部子公司：</dt>");
document.writeln("		<dd><a href=\"http://www.avire.com.cn/\">欧捷电梯部件</a> | <a href=\"http://www.advancedco.com/\">Advanced Electronics公司</a> | <a href=\"http://www.ffechina.com/\">消防事业有限公司</a> | <a href=\"http://www.bea-asiapacific.com/zh/\">比业电子</a> | <a href=\"http://www.texe.com.cn/\">泰斯康</a> | <a href=\"http://www.apollo-fire.cn/\">阿波罗消防产品</a></dd>");
document.writeln("		<dt>医疗设备事业部子公司：</dt>");
document.writeln("		<dd><a href=\"http://www.accudynamics.com/\">Accudynamics公司</a> | <a href=\"http://www.accutome.com/\">爱康泰</a> | <a href=\"http://www.medicel.com/cn/\">Medicel公司</a> | <a href=\"http://www.microsurgical.com/\">MST公司</a> | <a href=\"http://www.lgpump.com.cn/\">兰格恒流泵</a> | <a href=\"http://www.riester-china.cn/\">里斯特</a> | <a href=\"http://www.volkchina.cn/\">沃爱康光学</a> | <a href=\"http://www.biochemfluidics.com.cn/\">百柯流体</a> | <a href=\"http://www.keeler.co.uk/\">睛乐</a> | <a href=\"http://www.dibaind.cn/\">迪贝流体控制</a> | <a href=\"http://www.suntechmed.com.cn/\">顺泰医疗器械</a></dd>");
document.writeln("		<dt>环境与分析事业部子公司：</dt>");
document.writeln("		<dd><a href=\"http://www.avophotonics.com/\">Avo Photonics公司</a> | <a href=\"http://www.hydreka.com/\">Hydreka公司</a> | <a href=\"http://www.pixelteq.com/\">Pixelteq公司</a> | <a href=\"http://www.cosasco.com/\">Cosasco公司</a> | <a href=\"http://www.sensorex.com/\">Sensorex公司</a> | <a href=\"http://www.bersonuv.com/\">博生紫外线消毒</a> | <a href=\"http://www.oceanoptics.cn/\">海洋光学</a> | <a href=\"http://www.hanovia.com.cn/\">海诺威紫外线水处理</a> | <a href=\"http://www.palintest.com/\">百灵达</a> | <a href=\"http://www.permapure.com.cn/\">博纯</a> | <a href=\"http://www.alicat.com.cn/\">艾里卡特</a> | <a href=\"http://www.labsphere.com.cn/\">蓝菲光学</a> | <a href=\"http://www.hwmchina.cn/\">豪迈水管理</a> | <a href=\"http://www.fiberguide.com.cn/\">飞博盖德</a> | <a href=\"http://www.aquionics.com/\">Aquionics公司</a></dd>");
document.writeln("	</dl>");
document.writeln("    ");
document.writeln("    <div class=\"fotbot\">");
document.writeln("<p>Copyright © 2006-2015 Halma International Limited. All Rights Reserved <br/>");
document.writeln("© 2006-2015英国豪迈国际有限公司 版权所有 <a href=\"http://www.miibeian.gov.cn/\" rel=\"nofollow\" target=\"_blank\">沪ICP备09005869-1</a></p>");
document.writeln("</div>");
document.writeln("</div>");