//JavaScript Document
/*html*/
(function(win,doc){
        /*页面自适应*/
        var oContainer=doc.getElementById('container');
        var oHtml=doc.getElementsByTagName('html')[0];
        fnResetHtmlFontSize();
        function fnResetHtmlFontSize(){
                var iContainerWidth=oContainer.offsetWidth;
                oHtml.style.fontSize=iContainerWidth/10+'px';
        }
        win.addEventListener('resize',fnResetHtmlFontSize,false);
})(window,document);

document.writeln(" <header>");
document.writeln("                                <div class=\"header-nav\">");
document.writeln("                                        <ul>");
document.writeln("                                                <li></li>");
document.writeln("                                                <li></li>");
document.writeln("                                                <li><a href=\"tel:02223861215\"></a></li>");
document.writeln("                                        </ul>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"header-content\">");
document.writeln("                                        <h2><em></em></h2>");
document.writeln("                                        <div id=\"header-content\">");
document.writeln("                                                <div class=\"hd\" id=\"header-btn\">");
document.writeln("                                                        <ol>");
document.writeln("                                                                <li class=\"on\">关于我们</li>");
document.writeln("                                                                <li>皮肤科</li>");
document.writeln("                                                                <li>皮肤外科</li>");
document.writeln("                                                                <li>皮肤美容科</li>");
document.writeln("                                                        </ol>");
document.writeln("                                                </div>");
document.writeln("                                                <div class=\"bd\">");
document.writeln("                                                        <ul>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut1\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"/yyjj/\">津门简介</a>");
document.writeln("                                                                                        <a href=\"/mingyizhuanjia/\">专家介绍</a>");
document.writeln("                                                                                        <a href=\"/xianjinshebei/\">设备介绍</a>");
document.writeln("                                                                                        <a href=\"/dianxinganli/\">病友交流</a>");
document.writeln("                                                                                        <a href=\"/call.html/\">视频中心</a>");
document.writeln("                                                                                        <a href=\"/yiyuanrongyu/\">津门资讯</a>");
document.writeln("                                                                                        <a href=\"/zt/mtbd/\">社会公益</a>");
document.writeln("                                                                                        <a href=\"/zt/lylx/\">来院路线</a>");
document.writeln("                                                                                        <a href=\"/zt/mrjj/\">每日江城</a>");
document.writeln("                                                                                        <a href=\"/guahao/\">自助挂号</a>");
document.writeln("                                                                                       ");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut2\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"/zt/tslfnpx/\">牛皮癣</a>");
document.writeln("                                                                                        <a href=\"/zt/sz/\">湿疹</a>");
document.writeln("                                                                                        <a href=\"/zt/mny/\">毛囊炎</a>");
document.writeln("                                                                                        <a href=\"/zt/qcdzl/\">青春痘</a>");
document.writeln("                                                                                        <a href=\"/zt/zhzl/\">脱发</a>");
document.writeln("                                                                                        <a href=\"/zt/hzjzl/\">灰指甲</a>");
document.writeln("                                                                                        <a href=\"/zt/tslfbdf/\">白癜风</a>");
document.writeln("                                                                                        <a href=\"/zt/xmz/\">荨麻疹</a>");
document.writeln("                                                                                        <a href=\"/jibinglanmu/ylb.html\">鱼鳞病</a>");
document.writeln("                                                                                        <a href=\"/jibinglanmu/bpy.html\">扁平疣</a>");
document.writeln("                                                                                        <a href=\"/zt/py/\">皮炎</a>");
document.writeln("                                                                                        <a href=\"/zt/gm/\">皮肤过敏</a>");
document.writeln("                                                                                        <a href=\"/zt/xgl/\">小儿血管瘤</a>");
document.writeln("                                                                                        <a href=\"/zt/qdy/\">痘印</a>");
document.writeln(" ");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut3\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"/bahen/\">疤痕修复</a>");
document.writeln("                                                                                        <a href=\"/yc/\">腋臭</a>");
document.writeln("                                                                                        <a href=\"/zt/zf/\">植发</a>");
document.writeln("                                                                                        <a href=\"/zt/bhgd/\">疤痕疙瘩</a>");
document.writeln("                                                                                        <a href=\"/jibinglanmu/bzzt/bahen.html\">烧伤</a>");
document.writeln("                                                                                        <a href=\"/pifuxingbing/59582303.html\">尖利湿疣</a>");
document.writeln("                                                                                        <a href=\"/call.html\">黑毛痣</a>");
document.writeln("                                                                                        <a href=\"/call.html\">多指并指</a>");
document.writeln("                                                                                        <a href=\"/pifuxingbing/59582380.html\">性病自查</a>");
document.writeln("                                                                                        <a href=\"/pifuxingbing/59582387.html\">生殖器疱疹</a>");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut4\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"/call.html\">脂肪移植</a>");
document.writeln("                                                                                        <a href=\"/call.html\">溶脂紧肤</a>");
document.writeln("                                                                                        <a href=\"/call.html\">无创注射</a>");
document.writeln("                                                                                        <a href=\"/call.html\">隆鼻术</a>");
document.writeln("                                                                                        <a href=\"/call.html\">双眼皮</a>");
document.writeln("                                                                                        <a href=\"/call.html\">除皱</a>");
document.writeln("                                                                                        <a href=\"/jibinglanmu/xiwenshen/09714269.html\">洗纹身</a>");
document.writeln("                                                                                        <a href=\"/call.html\">美白</a>");
document.writeln("                                                                                        <a href=\"/call.html\">肉毒素</a>");
document.writeln("                                                                                        <a href=\"/zt/zhqb/\">祛斑</a>");
document.writeln("                                                                                        <a href=\"/call.html\">玻尿酸</a>");
document.writeln("                                                                                        <a href=\"/zt/qb/\">雀斑</a>");
document.writeln("                                                                                        <a href=\"/zt/hhb/\">黄褐斑</a>");
document.writeln("                                                                                        <a href=\"/meironglanmu/tuomao/tm.html\">脱毛</a>");
document.writeln("                                                                                        <a href=\"/zt/hxs/\">红血丝</a>");
document.writeln("                                                                                        <a href=\"/zt/tj/\">胎记</a>");
document.writeln("                                                                                        <a href=\"/zt/jzb/\">酒糟鼻</a>");
document.writeln("                                                                                      ");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                        </ul>");
document.writeln("                                                </div>");
document.writeln("                                        </div>");
document.writeln("                                </div>");
document.writeln("                        </header>");